volumes:
  volume-django:
    # name: volume-django
    # driver: local
    # driver_opts:
    # type: 'none'
    # o: 'bind'
      #      device: ${HOME}/data/volume-django

services:
  database:
    build:
      context: ./postgre
      dockerfile: Dockerfile
      args:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
    image: postgresql:transcendence
    container_name: postgre
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  
  django:
    build:
      context: ./django
      dockerfile: Dockerfile
    image: django:transcendence
    container_name: django
    restart: on-failure:10
  # Binds the HOST ~/data/volume-django -> CONTAINER /usr/src/app/ft_transcendence folder.
    volumes:
      - volume-django:/usr/src/app
    ports:
      - "8080:8000"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - database

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx:transcendence
    container_name: nginx
    restart: on-failure:10
    ports:
     - "443:443"
     - "80:80"
    volumes: 
     - /static
    depends_on:
     - django
