# Generated by Django 5.0.6 on 2024-06-28 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_customuser_image_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friends_list',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
