# Generated by Django 5.0.6 on 2024-06-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_customuser_friends_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'CustomUsers'},
        ),
    ]
