# Generated by Django 5.0.6 on 2024-06-29 17:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='latest_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
