# Generated by Django 4.2.13 on 2024-07-09 21:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_friendrequest_customuser_friends_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='friends_requests',
            field=models.ManyToManyField(related_name='friend_requesters', through='mainapp.FriendRequest', to=settings.AUTH_USER_MODEL),
        ),
    ]
